"""Yeni değişiklikler

Revision ID: 2af9d55a409b
Revises: a7a3a96e3be7
Create Date: 2024-11-10 01:32:43.576974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2af9d55a409b'
down_revision: Union[str, None] = 'a7a3a96e3be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
